// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fdaPDE2.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_Laplacian_2D_Order1();
RcppExport SEXP _rcpp_module_boot_SRPDE_Laplacian_2D_GeoStatNodes();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_Laplacian_2D_Order1", (DL_FUNC) &_rcpp_module_boot_Laplacian_2D_Order1, 0},
    {"_rcpp_module_boot_SRPDE_Laplacian_2D_GeoStatNodes", (DL_FUNC) &_rcpp_module_boot_SRPDE_Laplacian_2D_GeoStatNodes, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdaPDE2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
